local module = {
	{Name = "Apple", Cost = 2, Image = "rbxassetid://4784482033"},
	{Name = "Orange", Cost = 2, Image = "rbxassetid://6869120302"},
	{Name = "Banana", Cost = 3, Image = "rbxassetid://500109536"},
	{Name = "Eggs", Cost = 2, Image = "rbxassetid://11622456548"},
	{Name = "Pineapple", Cost = 5, Image = "rbxassetid://424045162"},
	{Name = "Water", Cost = 2, Image = "rbxassetid://11868682523"},
	{Name = "Cookie", Cost = 3, Image = "rbxassetid://482884517"},
	{Name = "Milk", Cost = 2, Image = "rbxassetid://5580971629"},
	{Name = "Flour", Cost = 3, Image = "rbxassetid://5614832381"},
	{Name = "Sugar", Cost = 1, Image = "rbxassetid://5614831823"},
	{Name = "Salt", Cost = 1, Image = "rbxassetid://5218039792"},
	{Name = "Pepper", Cost = 2, Image = "rbxassetid://193116232"}
}
return module
